# Generated by Django 4.2.6 on 2024-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, verbose_name='Имя преподавателя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('brief_info', models.CharField(max_length=400, verbose_name='Краткая информация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото преподавателя')),
                ('age', models.IntegerField(default=0)),
                ('experience', models.CharField(max_length=400, verbose_name='Профессиональный опыт')),
                ('add_info', models.CharField(max_length=1000, verbose_name='Дополнительная информация')),
                ('rating', models.IntegerField(default=0, verbose_name='Персональный рейтинг')),
                ('price', models.IntegerField(default=0)),
                ('lessons_amount', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['rating', 'name'],
            },
        ),
    ]
